# Generated by Django 2.1.3 on 2018-11-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larp_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='larp',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='larp',
            name='image',
            field=models.ImageField(upload_to='upload'),
        ),
    ]
