# Generated by Django 2.1.3 on 2018-11-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larp_calendar', '0003_auto_20181129_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='larp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='larp',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
